### ISSUE TITLE
could not decode zone JSONinvalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by lauer** [jamesorlakin/cert-manager-cpanel-dns-webhook#1]
Hi

Thanks for providing this plugin. I have however some problems in using it with my cpanel installation. 
I have tried to input if the `parse_zone` api reply into a test, but I can't reproduce the same error as in the deployment log. 

```
time="2022-09-26T19:37:33Z" level=info msg="Decoded webhook configuration {https://cpanel.mydomain.tld cert-manager/my-cpanel-credentials}"
time="2022-09-26T19:37:33Z" level=debug msg="Fetching contents of secret my-cpanel-credentials from namespace cert-manager"
time="2022-09-26T19:37:34Z" level=info msg="Got username and password from secret"
time="2022-09-26T19:37:34Z" level=info msg="Setting TXT record for '_acme-challenge.my.domain.tld.' to '<code>'"
time="2022-09-26T19:37:34Z" level=debug msg="Calculated record name '_acme-challenge.my' for zone 'domain.tld.'"
time="2022-09-26T19:37:35Z" level=error msg="could not decode zone JSONinvalid character '<' looking for beginning of value"
```

Could it be that it end with a `.` in the domain name - because it does not seems to do so in the tests.

**Comment by jamesorlakin** [comment]
Hi there!

Sorry to hear you're having trouble with the plugin. It was something I knocked up rather quickly but it's been running on my home cluster without any issues.

My gut instinct would be to manually create requests to your CPanel instance and see what it comes back with. From the log it looks like it's returning HTML for whatever reason - I noticed this seems to happen in some unauthorized scenarios when playing within Insomnia just now, especially if cookies are sent representing a session that isn't logged in (which shouldn't be the case as I'm not using a cookie jar in Go's HTTP client). cert-manager adds the trailing dot to DNS records but the code strips it out for CPanel (though good point, I'm not sure why I didn't include that aspect in the tests!) I really should add the attempted URL to the debug log output too.

Did you mention you successfully called `parse_zone` yourself manually? E.g. `https://cpanel.mydomain.tld/cpsess123/execute/DNS/parse_zone?zone=mydomain.tld` with HTTP Basic auth and no cookies:
![image](https://user-images.githubusercontent.com/7294642/192647865-125daf83-aeff-479d-99aa-e6b914250dee.png)

Sadly CPanel's UAPI doesn't feel to be the most robust of implementations but it could be something very simple I've overlooked. For example, on my installation not having `cpsessXXX` in the URL causes a 401 response* even though the docs suggest it shouldn't be needed at all. Another [page](https://docs.cpanel.net/knowledge-base/security/basic-security-concepts/) seems to suggest this security token is only needed if enabled, so I wonder if that's a difference on our CPanel instances?

*and then after writing that it starts working without the `cpsessXXX` bit in Insomnia after not working yesterday, how odd. 😕

**Comment by lauer** [comment]
Thanks for the quick help. 
I am able to request using postman and the generated api key in the header format like this

`Authorization: cpanel <username>:<API_KEY>`

As described in the documentation here: 
https://docs.cpanel.net/knowledge-base/security/how-to-use-cpanel-api-tokens/#run-api-functions-with-the-token

But it does not work with basic auth, as you describe, and I can see in the code, that you are using the basic auth method.
I can also get a 401 with the header solution, when my session expired for some reason. So you are right, it seems pretty unstable. It does sometimes help to clear cookies in postman.

But maybe you could make (or show me how I easy can build my own) a version which use the header instead?

The cpanel version is 106.

**Comment by jamesorlakin** [comment]
> a version which use the header instead?

I think that's a sensible idea. I can look to adding a new config option to try API keys under 'cpanel' Authorization instead of passwords. I also want to improve the logging a tad.

I won't get around to this until the weekend though.

**Comment by h00lig4n** [comment]
cpsess123 shouldn't be needed when using the authorization header.
Should be enough with:
yourcpanelurl:2083/execute/DNS/parse_zone?zone=domain

**Comment by jamesorlakin** [comment]
@h00lig4n I agree but at the time for some reason I sometimes got a 401 on my web host's instance without it. I now realise it could've just been cookies in my API tool though. I'll probably remove it. It's also a little strange how the URL examples in the doc pages also includes it.

**Comment by jamesorlakin** [comment]
I believe I've made the necessary changes and have API Tokens working locally. Feel free to give the `jamesorlakin/cert-manager-cpanel-dns-webhook:beta-api-keys-1` image a go and let me know if that works for you. If it does then I'll merge and push it as v1.1.0.

You'll need to set the API Token into a different property in the secret:
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: some-cpanel-credentials
  namespace: cert-manager
stringData:
  username: my-cpanel-user
  apiToken: ABCDEF1234567890ABCDEFABCDEF1234567890
```

**Comment by h00lig4n** [comment]
Hi,

I'm getting this issue: exec /usr/local/bin/webhook: exec format error
I re-deployed the cpanel credentials secret and updated the image in the deployment.

I won't be able to retest until Saturday, due to a busines trip.

**Comment by jamesorlakin** [comment]
Hmm, well that's strange!
![image](https://user-images.githubusercontent.com/7294642/193449728-ccc40076-e61a-4cd1-b166-46b85f524b24.png)

This beta image is currently only x86/AMD64, by chance are you trying to run it on arm64 (e.g. a Raspberry Pi)? I haven't quite got around to setting up Docker buildx again quite yet...

**Comment by h00lig4n** [comment]
Yes it's a ARM64 (Pi). Hopefully @lauer is running x86/AMD64 and can test it.

**Comment by lauer** [comment]
It's works fine on my setup (Proxmox on Intel(R) Core(TM) i7-6700T)
Thanks a lot @jamesorlakin for the quick fix.

**Comment by jamesorlakin** [comment]
I've merged and pushed this under the image `jamesorlakin/cert-manager-cpanel-dns-webhook:v0.2.0`. It should be multi-arch and is currently running on my Pi 4.
