### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by h00lig4n** [jamesorlakin/cert-manager-cpanel-dns-webhook#4]
The readme file refers to:
kubectl apply https://raw.githubusercontent.com/jamesorlakin/cert-manager-cpanel-dns-webhook/master/deploy/v0.1.0.yaml

I guess it should be 0.2.0 now ? You could also have -f before the url too.

**Comment by jamesorlakin** [comment]
Aah yep, excellent spot!
